---
name: test
on: pull_request
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            update-aqua-checksums:
              - aqua.yaml
              - aqua/*.yaml
              - aqua-checksums.json
              - .github/workflows/test.yaml
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/wc-renovate-config-validator.yaml
              - .github/workflows/test.yaml

  status-check:
    uses: ./.github/workflows/wc-test.yaml
    needs:
      - renovate-config-validator
      - update-aqua-checksums
      - test
    permissions: {}
    # https://github.com/orgs/community/discussions/45058
    # https://github.com/actions/runner/issues/491
    # This job is run when all needs' jobs succeed and the pull request is created by Renovate and Renovate's automerge is enabled.
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')

  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: ./.github/workflows/wc-renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  update-aqua-checksums:
    needs: path-filter
    if: needs.path-filter.outputs.update-aqua-checksums == 'true'
    uses: ./.github/workflows/wc-update-aqua-checksums.yaml
    permissions:
      contents: read
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  test:
    uses: ./.github/workflows/wc-test.yaml
    permissions: {}
