---
name: update-aqua-checksums
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
jobs:
  update-aqua-checksums:
    # Update aqua-checksums.json and push a commit
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@8ced7928ac26262a50279c2f4e98261773c8b1af # v0.1.5
    permissions:
      contents: read
    with:
      aqua_version: v2.2.2
      prune: true
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
